global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "next-demo-1"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:4000"]

  - job_name: "next-demo-2"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:4020"]

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
